import { test, expect } from "@playwright/test";

test("deployed automatic education view keeps metric scope on desktop and mobile", async ({ page }) => {
  const site = process.env.DEPLOYMENT_URL;
  test.skip(!site, "Requires a deployed site URL");
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`${site}/`);
  await expect(page.locator("#school-map")).toHaveAttribute("data-map-ready", "true");
  const legend = page.getByTestId("metric-legend");
  await expect(legend).toContainText("165,958명");
  await expect(legend).toContainText("상대 집중도");
  await expect(page.getByRole("complementary")).not.toBeVisible();
  await page.getByRole("button", {name:"교육여건", exact:true}).click();
  await expect(legend).toContainText("학급당 학생수");
  await page.getByRole("button", {name:"작은학교", exact:true}).click();
  await expect(legend).toContainText("310교");
  await page.getByRole("button", {name:"특수교육", exact:true}).click();
  await expect(legend).toContainText("559학급");
  await page.getByRole("button", {name:"학교·통계", exact:true}).click();
  await page.getByRole("tab", {name:"시군 통계", exact:true}).click();
  await expect(legend).toContainText("559학급");
  await expect(page).toHaveURL(/issue=special-education/);
  await page.getByRole("button", {name:"지역 변화", exact:true}).click();
  await expect(legend).toContainText("시군 단위");
  await expect(legend).toContainText("2022→2026");
  await page.goto(`${site}/?indicator=special_classes`);
  await expect(legend).toContainText("800학급");
  await expect(legend).toContainText("특수학교 포함");
  await page.setViewportSize({width:390,height:844});
  await page.goto(`${site}/`);
  await page.getByRole("combobox", {name:"교육현황 빠른 선택"}).selectOption("special-education");
  await expect(legend).toContainText("559학급");
  await page.getByRole("button", {name:/^전체 지표/}).click();
  const menu = page.getByRole("dialog", {name:"전체 지표 선택"});
  await menu.getByRole("button", {name:"특수학교 수",exact:true}).click();
  await expect(legend).toContainText("11개교");
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({path:"test-results/deployed-education-city-mobile.png"});
  expect(errors).toEqual([]);
});
